### ISSUE TITLE
멀티 모듈 생성

### ISSUE THREAD

**Issue by lluke0** [ShyPolarBear/Android#1]
## 📌  Feature Issue
클린 아키텍처 모듈 생성

## 📝  To-do

- [x] app 모듈 생성
- [x] presentation 모듈 생성
- [x] domain 모듈 생성
- [x] data 모듈 생성
