### ISSUE TITLE
Sample에 Ui State 적용

### ISSUE THREAD

**Issue by BEEEAM-J** [ShyPolarBear/Android#18]
## 📌  Feature Issue

Sample 데이터를 받아오는 예제에 ui state를 적용하는 예시 추가

## 📝  To-do

- [x] state data class 추가
- [x] viewModel에 ui state 적용
- [x] activity, fragment에 ui state 적용
