### ISSUE TITLE
피드 상단 UI 구현

### ISSUE THREAD

**Issue by BEEEAM-J** [ShyPolarBear/Android#21]
## 📌  Feature Issue

피드 상단 ui 구현
디자인 구현을 위한 기본 세팅 (폰트, 색상)
bottom navigation bar 구현

## 📝  To-do

- [x] 상단 바 구현
- [x] Power Menu 라이브러리 추가
- [x] bottom navigation bar 구현
- [x] 프로젝트 전용 색상 정의
- [x] 프로젝트 전용 폰트 스타일 정의
