### ISSUE TITLE
Mock 서버 사용하여 피드 전체 조회, 피드 자세히보기 데이터 받아오기 테스트

### ISSUE THREAD

**Issue by BEEEAM-J** [ShyPolarBear/Android#36]
## 📌  Feature Issue

Mock 서버 사용하여 피드 전체 조회, 피드 자세히보기 데이터 받아오기 테스트

## 📝  To-do

- [x] Mock 서버 구현
- [x] 피드 전체 조회 데이터 받아오기
- [x] 피드 자세히보기 데이터 받아오기
