### ISSUE TITLE
메인 - 더보기, 내 정보 수정 ui 구현

### ISSUE THREAD

**Issue by BEEEAM-J** [ShyPolarBear/Android#42]
## 📌  Feature Issue

메인 - 더보기, 내 정보 수정 ui 구현

## 📝  To-do

- [x] Bottom Navigation View로 더보기 fragment로 이동 구현
- [x] 메인 - 더보기 ui 구현
- [x] 내 정보 수정 ui 구현
