### ISSUE TITLE
내 정보 수정 입력 정보 로직 구현

### ISSUE THREAD

**Issue by BEEEAM-J** [ShyPolarBear/Android#52]
## 📌  Feature Issue

닉네임 글자 수 검사, 휴대폰 번호 입력 시 자동으로 - 제거, 이메일 필터링

## 📝  To-do

- [x] 닉네임 글자 수 검사 로직 구현
- [x] 휴대폰 번호 입력 시 자동으로 - 제거 로직 구현
- [x] 이메일 필터링 로직 구현
