### ISSUE TITLE
피드 api 적용

### ISSUE THREAD

**Issue by BEEEAM-J** [ShyPolarBear/Android#61]
## 📌  Feature Issue

피드의 각 동작을 api와 연동 (테스트 X)

## 📝  To-do

- [x] 피드 삭제 api 적용
- [x] 피드 삭제 시 view 업데이트 
- [x] 피드 작성 api 적용
- [x] 피드 좋아요 api 적용
