### ISSUE TITLE
피드 api 적용 테스트, 수정

### ISSUE THREAD

**Issue by BEEEAM-J** [ShyPolarBear/Android#65]
## 📌  Feature Issue

피드 api 적용한 것들 테스트 후 수정

## 📝  To-do

- [x] 전체 피드 조회 api 테스트
- [x] 피드 상세 조회 api 테스트
- [x] 피드 좋아요 api 테스트
- [x] 피드 작성 api 테스트
- [x] 피드 삭제 api 테스트
- [x] 피드 수정 api 테스트
