### ISSUE TITLE
로그아웃 구현 및 적용하지 못한 api, 제한 사항 적용 

### ISSUE THREAD

**Issue by BEEEAM-J** [ShyPolarBear/Android#87]
## 📌  Feature Issue

로그아웃 기능 구현 및 세부적인 제한 사항들 추가

## 📝  To-do

- [x] 로그아웃 기능 구현
- [x] 내 정보 수정 시 닉네임 중복 검사 추가
- [x] 피드 작성 시 텍스트 수 제한
- [x] 댓글 작성 텍스트 수 제한
- [ ] 메인-마이 페이지에 연동되지 않은 페이지들 연동
