### ISSUE TITLE
Hilt 추가 및 compose 제거

### ISSUE THREAD

**Issue by BEEEAM-J** [ShyPolarBear/Android#9]
## 📌  Feature Issue

Hilt 사용하기 위한 기본적인 Setting

## 📝  To-do

- [x] Hilt Dependency 추가
- [x] DI 패키지 추가
- [x] Application class 추가
- [x] build gradle .kts 파일로 변환
- [x] compose 제거

**Comment by lluke0** [comment]
이슈에 ToDO를 아주 잘 분리하셨네요 최고입니다 ㅎㅎ
