### ISSUE TITLE
"댓글 남기는 중" 표시 기능 수정

### ISSUE THREAD

**Issue by BEEEAM-J** [ShyPolarBear/Android#90]
## 📌  Feature Issue

"댓글 남기는 중" 표시를 대댓글을 작성하는 경우에만 보이는 기능
ⓧ버튼 클릭 시 대댓글 모드 해제되는 기능

## 📝  To-do

- [x] 대댓글 작성하는 경우에만 보이도록 수정
- [x] 대댓글을 남기려는 댓글 작성자 닉네임 보여주기
- [x] ⓧ버튼 클릭 시 대댓글 모드 해제되도록 수정
